#!/usr/bin/env bash

set -euo pipefail

FOURBYTE_API_URL="${FOURBYTE_API_URL:-https://www.4byte.directory/api/v1/signatures/}"
OUTPUT_DIR="${OUTPUT_DIR:-public/signatures}"
RAW_EXPORT_FILE="${RAW_EXPORT_FILE:-$OUTPUT_DIR/fourbyte-signatures.csv}"
SORTED_EXPORT_FILE="${SORTED_EXPORT_FILE:-$OUTPUT_DIR/fourbyte-signatures-sorted.csv}"
LINES_PER_CHUNK="${LINES_PER_CHUNK:-65000}"
PAGE_SIZE="${PAGE_SIZE:-10000}"
TYPESCRIPT_FILE="${TYPESCRIPT_FILE:-src/utils/hash-lookup.ts}"
MAX_PAGES="${MAX_PAGES:-}"

require_command() {
  local cmd="$1"
  if ! command -v "$cmd" >/dev/null 2>&1; then
    echo "Missing required command: $cmd"
    exit 1
  fi
}

for cmd in curl sort split awk sed zstd node; do
  require_command "$cmd"
done

mkdir -p "$OUTPUT_DIR"

escape_ts_string() {
  printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'
}

suffix_to_decimal() {
  local suffix="$1"
  local decimal_value=0
  local i char value ascii

  for ((i = 0; i < ${#suffix}; i++)); do
    char=${suffix:$i:1}
    if [[ "$char" =~ [0-9] ]]; then
      value="$char"
    else
      ascii=$(printf '%d' "'${char,,}")
      value=$((ascii - 97 + 10))
    fi
    decimal_value=$((decimal_value * 36 + value))
  done

  echo "$decimal_value"
}

echo "Downloading signatures from $FOURBYTE_API_URL"
: >"$RAW_EXPORT_FILE"

next_url="${FOURBYTE_API_URL}?page=1&page_size=${PAGE_SIZE}"
page=1

while [[ -n "$next_url" ]]; do
  echo "  Fetching page $page"
  page_file="$(mktemp)"

  curl --fail --silent --show-error --location "$next_url" -o "$page_file"

  node -e '
const fs = require("fs")
const payload = JSON.parse(fs.readFileSync(process.argv[1], "utf8"))
for (const row of payload.results || []) {
  if (row.hex_signature && row.text_signature) {
    process.stdout.write(String(row.hex_signature).toLowerCase() + "," + row.text_signature + "\n")
  }
}
' "$page_file" >>"$RAW_EXPORT_FILE"

  next_url="$(
    node -e '
const fs = require("fs")
const payload = JSON.parse(fs.readFileSync(process.argv[1], "utf8"))
const next = typeof payload.next === "string" ? payload.next : ""
process.stdout.write(next.replace(/^http:\/\//, "https://"))
' "$page_file"
  )"
  rm -f "$page_file"

  if [[ -n "$MAX_PAGES" && "$page" -ge "$MAX_PAGES" ]]; then
    echo "Reached MAX_PAGES=$MAX_PAGES. Stopping early."
    break
  fi

  page=$((page + 1))
done

if [[ ! -s "$RAW_EXPORT_FILE" ]]; then
  echo "No signatures were downloaded. Exiting."
  exit 1
fi

echo "Sorting and grouping signatures by selector..."
LC_ALL=C sort -t',' -k1,1 -k2,2 "$RAW_EXPORT_FILE" |
  awk '
  function flush() {
    if (prev_hash != "") {
      print prev_hash "," signatures
    }
  }
  {
    split_pos = index($0, ",")
    if (split_pos == 0) next

    hash = substr($0, 1, split_pos - 1)
    sig = substr($0, split_pos + 1)

    if (hash != prev_hash) {
      flush()
      prev_hash = hash
      signatures = sig
      seen = ";" sig ";"
      next
    }

    needle = ";" sig ";"
    if (index(seen, needle) == 0) {
      signatures = signatures ";" sig
      seen = seen sig ";"
    }
  }
  END { flush() }
' >"$SORTED_EXPORT_FILE"

if [[ ! -s "$SORTED_EXPORT_FILE" ]]; then
  echo "Failed to build sorted signature export. Exiting."
  exit 1
fi

echo "Splitting sorted signature export into chunks..."
split -l "$LINES_PER_CHUNK" "$SORTED_EXPORT_FILE" "$OUTPUT_DIR/chunk_"

shopt -s nullglob
raw_chunks=("$OUTPUT_DIR"/chunk_*)

if [[ ${#raw_chunks[@]} -eq 0 ]]; then
  echo "No chunks were generated. Exiting."
  exit 1
fi

for chunk in "${raw_chunks[@]}"; do
  mv "$chunk" "$chunk.raw"
done

echo "Generating $TYPESCRIPT_FILE..."
cat >"$TYPESCRIPT_FILE" <<'EOF'
/**
 * Hash range lookup for transaction signatures
 *
 * This file is automatically generated by grab_split_db.sh
 * from the 4byte signature database.
 */

import { init, decompress } from '@bokuweb/zstd-wasm'

interface HashRange {
  file: string
  firstHash: string
  firstSig: string
  lastHash: string
  lastSig: string
}

const FILE_RANGES: HashRange[] = [
EOF

count=0
for chunk in "$OUTPUT_DIR"/chunk_*.raw; do
  chunk_basename="$(basename "$chunk")"
  chunk_suffix="${chunk_basename#chunk_}"
  chunk_number="${chunk_suffix%.raw}"

  decimal_value="$(suffix_to_decimal "$chunk_number")"
  padded_number="$(printf "%03d" $((decimal_value + 1)))"
  export_chunk_filename="export_chunk_$padded_number"

  first_line="$(head -n 1 "$chunk")"
  last_line="$(tail -n 1 "$chunk")"

  first_hash="${first_line%%,*}"
  first_sig="${first_line#*,}"
  last_hash="${last_line%%,*}"
  last_sig="${last_line#*,}"

  if [[ ! "$first_hash" =~ ^0x[0-9a-fA-F]{8}$ ]]; then
    echo "Skipping chunk with invalid first hash: $chunk_basename"
    continue
  fi

  if [[ ! "$last_hash" =~ ^0x[0-9a-fA-F]{8}$ ]]; then
    echo "Skipping chunk with invalid last hash: $chunk_basename"
    continue
  fi

  first_sig_escaped="$(escape_ts_string "$first_sig")"
  last_sig_escaped="$(escape_ts_string "$last_sig")"

  if [[ $count -gt 0 ]]; then
    echo "," >>"$TYPESCRIPT_FILE"
  fi

  cat >>"$TYPESCRIPT_FILE" <<EOF
  {
    file: "$export_chunk_filename",
    firstHash: "$first_hash",
    firstSig: "$first_sig_escaped",
    lastHash: "$last_hash",
    lastSig: "$last_sig_escaped"
  }
EOF

  count=$((count + 1))
done

cat >>"$TYPESCRIPT_FILE" <<'EOF'
]

export function findFileForHash(hash: string): string | null {
  const hashValue = parseInt(hash, 16)

  for (const range of FILE_RANGES) {
    const firstValue = parseInt(range.firstHash, 16)
    const lastValue = parseInt(range.lastHash, 16)

    if (hashValue >= firstValue && hashValue <= lastValue) {
      return range.file
    }
  }

  return null
}

let isInitialized = false
let initPromise: Promise<void> | null = null
const fileContentCache = new Map<string, string>()

async function initZstd(): Promise<void> {
  if (!isInitialized && !initPromise) {
    initPromise = init().then(() => {
      isInitialized = true
    })
  }
  return initPromise || Promise.resolve()
}

async function decompressZstd(compressedData: ArrayBuffer): Promise<string> {
  await initZstd()

  const compressedArray = new Uint8Array(compressedData)
  const decompressedArray = decompress(compressedArray)

  const decoder = new TextDecoder('utf-8')
  return decoder.decode(decompressedArray)
}

export async function getFunctionSignature(hash: string): Promise<string | null> {
  const normalizedHash = (hash.startsWith('0x') ? hash : `0x${hash}`).toLowerCase()

  const fileName = findFileForHash(normalizedHash)
  if (!fileName) {
    return null
  }

  try {
    let fileContent = fileContentCache.get(fileName)

    if (!fileContent) {
      const response = await fetch(`/signatures/${fileName}`)
      if (!response.ok) {
        return null
      }

      const compressedData = await response.arrayBuffer()

      fileContent = await decompressZstd(compressedData)
      fileContentCache.set(fileName, fileContent)
    }

    const lines = fileContent.split('\n')
    for (const line of lines) {
      if (line.startsWith(normalizedHash + ',')) {
        return line.substring(normalizedHash.length + 1)
      }
    }

    return null
  } catch (_error) {
    return null
  }
}
EOF

echo "Compressing chunks with zstd..."
for chunk in "$OUTPUT_DIR"/chunk_*.raw; do
  chunk_basename="$(basename "$chunk")"
  chunk_suffix="${chunk_basename#chunk_}"
  chunk_number="${chunk_suffix%.raw}"

  decimal_value="$(suffix_to_decimal "$chunk_number")"
  padded_number="$(printf "%03d" $((decimal_value + 1)))"
  export_chunk_filename="export_chunk_$padded_number"
  output_file="$OUTPUT_DIR/$export_chunk_filename"

  zstd -19 --quiet "$chunk" -o "$output_file"
done

rm -f "$OUTPUT_DIR"/chunk_*.raw "$SORTED_EXPORT_FILE"

echo "Done."
echo "Stored API export in: $RAW_EXPORT_FILE"
echo "Generated lookup file: $TYPESCRIPT_FILE"
echo "Compressed chunk files are in: $OUTPUT_DIR"
