#!/bin/bash

# Config
EXPORT_URL="https://api.openchain.xyz/signature-database/v1/export"
TEMP_EXPORT_FILE="/tmp/db_export_downloaded"
OUTPUT_DIR="public/tx-decoder-tmp"
LINES_PER_CHUNK=65000  # Adjust as needed to get desired file sizes
TYPESCRIPT_FILE="hash-lookup.ts"

# Ensure output directory exists
mkdir -p "$OUTPUT_DIR"
mkdir -p "/tmp/db_export"  # Create temp directory for download

# Step 0: Download the export file
echo "Downloading export file from $EXPORT_URL..."
wget -O "$TEMP_EXPORT_FILE" "$EXPORT_URL"

if [ $? -ne 0 ]; then
    echo "Failed to download the export file. Exiting."
    exit 1
fi

echo "Download complete."

# Count total lines in the file
echo "Counting total lines in file..."
TOTAL_LINES=$(wc -l < "$TEMP_EXPORT_FILE")
echo "Total lines: $TOTAL_LINES"

# Calculate number of chunks needed
CHUNK_COUNT=$(( (TOTAL_LINES + LINES_PER_CHUNK - 1) / LINES_PER_CHUNK ))
echo "Will create $CHUNK_COUNT chunks with approximately $LINES_PER_CHUNK lines each"

echo "Step 1: Splitting the file into chunks by line boundaries..."
# Use split to create chunks with a specified number of lines
split -l "$LINES_PER_CHUNK" "$TEMP_EXPORT_FILE" "$OUTPUT_DIR/chunk_"

# Rename chunks to have .raw extension for clarity
for chunk in "$OUTPUT_DIR"/chunk_*; do
  if [[ ! "$chunk" == *.raw ]]; then
    mv "$chunk" "$chunk.raw"
  fi
done

echo "Step 2: Getting the first and last lines from each chunk for hash ranges..."
# Start writing the TypeScript file with the header
cat > "$TYPESCRIPT_FILE" << 'EOF'
/**
 * Hash range lookup for transaction signatures
 * 
 * This file is automatically generated from export file chunks
 * Each chunk contains function signatures with their corresponding hashes
 * Format: 0xHASH,functionSignature(param1,param2)
 */

/**
 * Interface representing a hash range within a specific file
 */
interface HashRange {
  /** Filename containing the hash range */
  file: string;
  /** First hash in the file */
  firstHash: string;
  /** First function signature in the file */
  firstSig: string;
  /** Last hash in the file */
  lastHash: string;
  /** Last function signature in the file */
  lastSig: string;
}

/**
 * Array of hash ranges, with first and last hash/signature from each file
 */
const FILE_RANGES: HashRange[] = [
EOF

# Process each raw chunk to extract its first and last lines
count=0
for chunk in "$OUTPUT_DIR"/chunk_*.raw; do
  # Extract chunk number from filename to create sequential numbered output files
  chunk_basename=$(basename "$chunk")
  chunk_suffix=${chunk_basename#chunk_}
  chunk_number=${chunk_suffix%.raw}
  
  # Convert to padded decimal number
  # First, convert from base 36 to decimal (macOS split uses a-z after 0-9)
  decimal_value=0
  for (( i=0; i<${#chunk_number}; i++ )); do
    char=${chunk_number:$i:1}
    if [[ $char =~ [0-9] ]]; then
      value=$char
    else
      # Convert a-z to 10-35
      value=$(( $(printf "%d" "'$char") - $(printf "%d" "'a") + 10 ))
    fi
    decimal_value=$(( decimal_value * 36 + value ))
  done
  
  # Format with padding
  padded_number=$(printf "%02d" $((decimal_value + 1)))
  export_chunk_filename="export_chunk_$padded_number"
  
  echo "Processing chunk: $chunk_basename to $export_chunk_filename"
  
  # Extract first and last lines
  first_line=$(head -n 1 "$chunk")
  last_line=$(tail -n 1 "$chunk")
  
  # Validate first line format (must start with 0x)
  if [[ ! "$first_line" =~ ^0x[0-9a-fA-F]+ ]]; then
    echo "Warning: First line in $chunk_basename doesn't match expected format: $first_line"
    continue
  fi
  
  # Validate last line format (must start with 0x)
  if [[ ! "$last_line" =~ ^0x[0-9a-fA-F]+ ]]; then
    echo "Warning: Last line in $chunk_basename doesn't match expected format: $last_line"
    continue
  fi
  
  # Parse hash and signature from first line
  first_hash=$(echo "$first_line" | cut -d',' -f1)
  first_sig=$(echo "$first_line" | cut -d',' -f2-)
  
  # Parse hash and signature from last line
  last_hash=$(echo "$last_line" | cut -d',' -f1)
  last_sig=$(echo "$last_line" | cut -d',' -f2-)
  
  # Add comma if not the first entry
  if [ $count -gt 0 ]; then
    echo "," >> "$TYPESCRIPT_FILE"
  fi
  
  # Properly escape quotes for JavaScript
  first_sig=$(echo "$first_sig" | sed 's/"/\\"/g')
  last_sig=$(echo "$last_sig" | sed 's/"/\\"/g')
  
  # Write this file's range to the TypeScript file
  cat >> "$TYPESCRIPT_FILE" << EOF
  {
    file: "$export_chunk_filename",
    firstHash: "$first_hash",
    firstSig: "$first_sig",
    lastHash: "$last_hash",
    lastSig: "$last_sig"
  }
EOF
  
  echo "  Extracted range from $chunk_basename: $first_hash to $last_hash"
  count=$((count + 1))
done

# Close the array and add the lookup function
cat >> "$TYPESCRIPT_FILE" << 'EOF'
];

/**
 * Finds the file that contains the given hash
 * 
 * @param hash - The function hash to look up (format: '0x...')
 * @returns The filename containing the hash, or null if not found
 */
export function findFileForHash(hash: string): string | null {
  // Convert hash to numeric value for comparison
  const hashValue = parseInt(hash, 16);
  
  for (const range of FILE_RANGES) {
    // Convert first and last hashes to numeric values
    const firstValue = parseInt(range.firstHash, 16);
    const lastValue = parseInt(range.lastHash, 16);
    
    // Check if the hash falls within this file's range
    if (hashValue >= firstValue && hashValue <= lastValue) {
      return range.file;
    }
  }
  
  // If no range matched, return null
  return null;
}
EOF

echo "Step 3: Compressing each chunk with zstd..."
# Now compress each raw chunk
for chunk in "$OUTPUT_DIR"/chunk_*.raw; do
  # Extract chunk number from filename to create sequential numbered output files
  chunk_basename=$(basename "$chunk")
  chunk_suffix=${chunk_basename#chunk_}
  chunk_number=${chunk_suffix%.raw}
  
  # Convert to padded decimal number
  # First, convert from base 36 to decimal (macOS split uses a-z after 0-9)
  decimal_value=0
  for (( i=0; i<${#chunk_number}; i++ )); do
    char=${chunk_number:$i:1}
    if [[ $char =~ [0-9] ]]; then
      value=$char
    else
      # Convert a-z to 10-35
      value=$(( $(printf "%d" "'$char") - $(printf "%d" "'a") + 10 ))
    fi
    decimal_value=$(( decimal_value * 36 + value ))
  done
  
  # Format with padding
  padded_number=$(printf "%02d" $((decimal_value + 1)))
  export_chunk_filename="export_chunk_$padded_number"
  output_file="$OUTPUT_DIR/$export_chunk_filename"
  
  echo "  Compressing $chunk_basename to $export_chunk_filename..."
  zstd -19 "$chunk" -o "$output_file"
done

echo "Step 4: Cleaning up temporary raw chunks and downloaded file..."
# Clean up the raw chunks and downloaded file
rm "$OUTPUT_DIR"/chunk_*.raw
rm "$TEMP_EXPORT_FILE"

echo "Done! Created $count compressed chunks and TypeScript lookup file."
echo "TypeScript file: $TYPESCRIPT_FILE"
echo "Compressed files are in: $OUTPUT_DIR"