/**
 * Hash range lookup for transaction signatures
 *
 * This file is automatically generated by grab_split_db.sh
 * from the 4byte signature database.
 */

import { init, decompress } from '@bokuweb/zstd-wasm'

interface HashRange {
  file: string
  firstHash: string
  lastHash: string
}

const FILE_RANGES: HashRange[] = [
  {
    file: 'export_chunk_371',
    firstHash: '0x00000000',
    lastHash: '0x0e316ab7',
  },
  {
    file: 'export_chunk_372',
    firstHash: '0x0e31b50e',
    lastHash: '0x1c70cc49',
  },
  {
    file: 'export_chunk_373',
    firstHash: '0x1c70ce3f',
    lastHash: '0x2aac9ee0',
  },
  {
    file: 'export_chunk_374',
    firstHash: '0x2aaca0fa',
    lastHash: '0x38f77d69',
  },
  {
    file: 'export_chunk_375',
    firstHash: '0x38f7a867',
    lastHash: '0x4723affc',
  },
  {
    file: 'export_chunk_376',
    firstHash: '0x4723bf7a',
    lastHash: '0x55614cfa',
  },
  {
    file: 'export_chunk_377',
    firstHash: '0x55614fcc',
    lastHash: '0x63b2c2a9',
  },
  {
    file: 'export_chunk_378',
    firstHash: '0x63b2d0f6',
    lastHash: '0x71ea7b7b',
  },
  {
    file: 'export_chunk_379',
    firstHash: '0x71ea87ee',
    lastHash: '0x80361c73',
  },
  {
    file: 'export_chunk_380',
    firstHash: '0x8036268e',
    lastHash: '0x8e7fd292',
  },
  {
    file: 'export_chunk_381',
    firstHash: '0x8e7fdc6c',
    lastHash: '0x9cae6f49',
  },
  {
    file: 'export_chunk_382',
    firstHash: '0x9cae7da5',
    lastHash: '0xaaf97b68',
  },
  {
    file: 'export_chunk_383',
    firstHash: '0xaaf9ac80',
    lastHash: '0xb918866b',
  },
  {
    file: 'export_chunk_384',
    firstHash: '0xb918a18a',
    lastHash: '0xc74c6540',
  },
  {
    file: 'export_chunk_385',
    firstHash: '0xc74c6bfa',
    lastHash: '0xd5897182',
  },
  {
    file: 'export_chunk_386',
    firstHash: '0xd5897504',
    lastHash: '0xe3c0ff12',
  },
  {
    file: 'export_chunk_387',
    firstHash: '0xe3c10714',
    lastHash: '0xf1f169e7',
  },
  {
    file: 'export_chunk_388',
    firstHash: '0xf1f1d481',
    lastHash: '0xffffffff',
  },
]

export function findFileForHash(hash: string): string | null {
  const hashValue = parseInt(hash, 16)

  for (const range of FILE_RANGES) {
    const firstValue = parseInt(range.firstHash, 16)
    const lastValue = parseInt(range.lastHash, 16)

    if (hashValue >= firstValue && hashValue <= lastValue) {
      return range.file
    }
  }

  return null
}

let isInitialized = false
let initPromise: Promise<void> | null = null
const fileContentCache = new Map<string, string>()

async function initZstd(): Promise<void> {
  if (!isInitialized && !initPromise) {
    initPromise = init().then(() => {
      isInitialized = true
    })
  }
  return initPromise || Promise.resolve()
}

async function decompressZstd(compressedData: ArrayBuffer): Promise<string> {
  await initZstd()

  const compressedArray = new Uint8Array(compressedData)
  const decompressedArray = decompress(compressedArray)

  const decoder = new TextDecoder('utf-8')
  return decoder.decode(decompressedArray)
}

export async function getFunctionSignature(hash: string): Promise<string | null> {
  const normalizedHash = (hash.startsWith('0x') ? hash : `0x${hash}`).toLowerCase()

  const fileName = findFileForHash(normalizedHash)
  if (!fileName) {
    return null
  }

  try {
    let fileContent = fileContentCache.get(fileName)

    if (!fileContent) {
      const response = await fetch(`/signatures/${fileName}`)
      if (!response.ok) {
        return null
      }

      const compressedData = await response.arrayBuffer()

      fileContent = await decompressZstd(compressedData)
      fileContentCache.set(fileName, fileContent)
    }

    const lines = fileContent.split('\n')
    for (const line of lines) {
      if (line.startsWith(normalizedHash + ',')) {
        return line.substring(normalizedHash.length + 1)
      }
    }

    return null
  } catch (_error) {
    return null
  }
}
