/**
 * Hash range lookup for transaction signatures
 *
 * This file is automatically generated from export file chunks
 * Each chunk contains function signatures with their corresponding hashes
 * Format: 0xHASH,functionSignature(param1,param2)
 *
 * The files are compressed using zstd compression and need to be decompressed
 * before parsing.
 */

import { init, decompress } from '@bokuweb/zstd-wasm'

/**
 * Interface representing a hash range within a specific file
 */

interface HashRange {
  file: string
  firstHash: string
  firstSig: string
  lastHash: string
  lastSig: string
}

const FILE_RANGES: HashRange[] = [
  {
    file: 'export_chunk_371',
    firstHash: '0x00000000',
    firstSig: 'blockHashAmphithyronVersify(uint256)',
    lastHash: '0x06255eac',
    lastSig: 'cliff(address,bool)',
  },
  {
    file: 'export_chunk_372',
    firstHash: '0x06256bdd',
    firstSig: 'getMaxStakeLeadPercent(uint256)',
    lastHash: '0x0c491e0e',
    lastSig: 'revisedAmountOwed()',
  },
  {
    file: 'export_chunk_373',
    firstHash: '0x0c492500',
    firstSig: 'totalV1()',
    lastHash: '0x126f68f3',
    lastSig: 'setupBlindBoxInfo(uint8,uint256,uint32,uint256)',
  },
  {
    file: 'export_chunk_374',
    firstHash: '0x126f6d59',
    firstSig: '_cj_poaps()',
    lastHash: '0x1892ff9d',
    lastSig: 'endBid(address[],uint256[],uint256,address,bytes,uint256)',
  },
  {
    file: 'export_chunk_375',
    firstHash: '0x1892ffae',
    firstSig: 'manage_Launch(address[],bool)',
    lastHash: '0x1ebecec4',
    lastSig: 'MAGICairdrop(address)',
  },
  {
    file: 'export_chunk_376',
    firstHash: '0x1ebed04d',
    firstSig: 'updateUserReleaseTokenAmount(address)',
    lastHash: '0x24e0d460',
    lastSig: 'variableRate()',
  },
  {
    file: 'export_chunk_377',
    firstHash: '0x24e0e18f',
    firstSig: 'fc101_ad6b310b_0_0(uint256)',
    lastHash: '0x2b00f528',
    lastSig: 'updateStakingReward(address,uint256,uint256,uint256,uint256,uint256,uint256)',
  },
  {
    file: 'export_chunk_378',
    firstHash: '0x2b00f634',
    firstSig: 'ramdom1()',
    lastHash: '0x312fef55',
    lastSig: 'setNoSellLimt(uint256)',
  },
  {
    file: 'export_chunk_379',
    firstHash: '0x312ff839',
    firstSig: 'processExpiredLocks(bool)',
    lastHash: '0x374eaed4',
    lastSig: 'NoTokensSpecified()',
  },
  {
    file: 'export_chunk_380',
    firstHash: '0x374eb2bc',
    firstSig: 'getProportionalVolatility(uint256,uint256)',
    lastHash: '0x3d78a28b',
    lastSig: 'setPricesAndExecute(address[],uint256[],uint256,uint256,uint256,uint256,uint256)',
  },
  {
    file: 'export_chunk_381',
    firstHash: '0x3d78a7ee',
    firstSig: '_HoldersFee()',
    lastHash: '0x439fa351',
    lastSig: 'createLaunchPool(address[],uint256[],string,address,uint16,address)',
  },
  {
    file: 'export_chunk_382',
    firstHash: '0x439fab07',
    firstSig: 'canRevoke(uint256)',
    lastHash: '0x49bc990b',
    lastSig: 'mint(uint112,uint112)',
  },
  {
    file: 'export_chunk_383',
    firstHash: '0x49bc9952',
    firstSig: 'mintKudos(address[],bytes32[])',
    lastHash: '0x4fdeb9b2',
    lastSig:
      'newPartiallyInvestLiquidateSetPositionLeverageMaxValidateAdminValueOutOfPartial((uint256,uint256,uint16,address,bool,uint8,uint256,uint256,uint256,uint256,bytes))',
  },
  {
    file: 'export_chunk_384',
    firstHash: '0x4fdebadf',
    firstSig: 'GetClaimableReward(uint256)',
    lastHash: '0x56041432',
    lastSig: 'sharedFiles(address,uint256)',
  },
  {
    file: 'export_chunk_385',
    firstHash: '0x56041c35',
    firstSig: 'Distributions__NoKarmaInThisRound()',
    lastHash: '0x5c2cc930',
    lastSig: 'getConvertionInUSD(uint256)',
  },
  {
    file: 'export_chunk_386',
    firstHash: '0x5c2ccaba',
    firstSig: 'GslStandardToken(uint256,string,uint8,string)',
    lastHash: '0x625a40e6',
    lastSig: 'Failed()',
  },
  {
    file: 'export_chunk_387',
    firstHash: '0x625a43fe',
    firstSig: 'ManagerOnly(address,address)',
    lastHash: '0x687fcdc0',
    lastSig: 'cryptoRare3()',
  },
  {
    file: 'export_chunk_388',
    firstHash: '0x687fd6dc',
    firstSig: 'revardGenerates()',
    lastHash: '0x6ea60342',
    lastSig: '_standardToken()',
  },
  {
    file: 'export_chunk_389',
    firstHash: '0x6ea606b7',
    firstSig:
      'newOrInvestSharesVaultPositionLiquidateMaxValidateAdminTokensRemoveLiquidityRewardsSetOpenCloseValuePartiallyOfAnd((uint256,uint256,uint16,address,bool,uint8,uint256,uint256,uint256,uint256,bytes))',
    lastHash: '0x74d3b5c1',
    lastSig: 'setLastRequestTime(string,uint256)',
  },
  {
    file: 'export_chunk_390',
    firstHash: '0x74d3b7cd',
    firstSig: 'LTR3Token()',
    lastHash: '0x7af70ee0',
    lastSig: 'setExecude(address,bool)',
  },
  {
    file: 'export_chunk_391',
    firstHash: '0x7af71a83',
    firstSig: 'migrate(uint32,address,string,address,uint256)',
    lastHash: '0x81244d51',
    lastSig: 'reserveAddresses(uint256)',
  },
  {
    file: 'export_chunk_392',
    firstHash: '0x81244e3e',
    firstSig: 'createVault(address,uint256,address,uint256,bool)',
    lastHash: '0x874d947b',
    lastSig: 'setWhitelistUserMerkleRoot(bytes32)',
  },
  {
    file: 'export_chunk_393',
    firstHash: '0x874d9a50',
    firstSig: 'userVeGrvInfo(address)',
    lastHash: '0x8d7ad059',
    lastSig: 'updateStartEpoch(uint256)',
  },
  {
    file: 'export_chunk_394',
    firstHash: '0x8d7ad17b',
    firstSig: 'cacheCH0()',
    lastHash: '0x93a2e6d5',
    lastSig: 'getParentCount(uint256)',
  },
  {
    file: 'export_chunk_395',
    firstHash: '0x93a2e71e',
    firstSig: 'getAllStakedGB()',
    lastHash: '0x99c76d56',
    lastSig: 'developerMarketingWalletAddress()',
  },
  {
    file: 'export_chunk_396',
    firstHash: '0x99c7759b',
    firstSig: 'parseTradeArgs()',
    lastHash: '0x9fe98708',
    lastSig: 'getAllUnstakeData(address,address)',
  },
  {
    file: 'export_chunk_407',
    firstHash: '0x9fe98bda',
    firstSig: 'reclaimTokenTo(address,address,uint256)',
    lastHash: '0xa60b8868',
    lastSig: 'b32ToStr(bytes32)',
  },
  {
    file: 'export_chunk_408',
    firstHash: '0xa60b89c9',
    firstSig: 'nftPriceWL()',
    lastHash: '0xac35f02c',
    lastSig: 'getLpPairAddress()',
  },
  {
    file: 'export_chunk_409',
    firstHash: '0xac360033',
    firstSig: 'release_from(address,uint256,string)',
    lastHash: '0xb259ee08',
    lastSig: 'mintLandSSB(uint256,uint256)',
  },
  {
    file: 'export_chunk_410',
    firstHash: '0xb259ee34',
    firstSig: '_updateUserWithdrawFee()',
    lastHash: '0xb87ea5d1',
    lastSig: 'HNYDeposit(uint256)',
  },
  {
    file: 'export_chunk_411',
    firstHash: '0xb87ea891',
    firstSig: 'getWithdrawableCoverNotesAmount(address)',
    lastHash: '0xbea36eff',
    lastSig: '_GetSupply()',
  },
  {
    file: 'export_chunk_412',
    firstHash: '0xbea37984',
    firstSig: 'mint721A(address,address)',
    lastHash: '0xc4c050f6',
    lastSig: 'iterableAccountMarkets(address)',
  },
  {
    file: 'export_chunk_413',
    firstHash: '0xc4c0567b',
    firstSig: 'totalUserBalance()',
    lastHash: '0xcae683af',
    lastSig:
      'sharesCloseInvestAndOutRangeLeverageMaxValidateRepayTokensReToken0PartiallyState((uint256,uint256,uint16,address,bool,uint8,uint256,uint256,uint256,uint256,bytes))',
  },
  {
    file: 'export_chunk_414',
    firstHash: '0xcae685d4',
    firstSig:
      'newRemoveReStateSharesOfToken0MaxCloseRangeOutReinvestLiquidityLiquidate((uint256,uint256,uint16,address,bool,uint8,uint256,uint256,uint256,uint256,bytes))',
    lastHash: '0xd1120db0',
    lastSig: 'size2()',
  },
  {
    file: 'export_chunk_415',
    firstHash: '0xd1120ff5',
    firstSig: 'sellerDetails(address)',
    lastHash: '0xd73fa1c7',
    lastSig: '_percentValue(uint256,uint8)',
  },
  {
    file: 'export_chunk_416',
    firstHash: '0xd73fafea',
    firstSig: 'teamMemberList()',
    lastHash: '0xdd6ad764',
    lastSig: 'withdraw(uint8,address)',
  },
  {
    file: 'export_chunk_417',
    firstHash: '0xdd6ad932',
    firstSig: 'checkPlayers()',
    lastHash: '0xe38c3045',
    lastSig: 'toPositionTokens((uint256,uint256,uint16,address,bool,uint8,uint256,uint256,uint256,uint256,bytes))',
  },
  {
    file: 'export_chunk_418',
    firstHash: '0xe38c3486',
    firstSig: 'setTickSize(address,uint256)',
    lastHash: '0xe9ae52fd',
    lastSig: 'countDayFour()',
  },
  {
    file: 'export_chunk_419',
    firstHash: '0xe9ae54f7',
    firstSig: 'setOpeningTransferDate(uint256)',
    lastHash: '0xefd111f2',
    lastSig: 'mintEusdRequestVia3pool((address,uint256,uint256,address,uint256,address),(address,uint256,uint256))',
  },
  {
    file: 'export_chunk_420',
    firstHash: '0xefd11b87',
    firstSig: 'getIsNodeMembers(address)',
    lastHash: '0xf60129d4',
    lastSig: 'nigDSd()',
  },
  {
    file: 'export_chunk_421',
    firstHash: '0xf6012bcc',
    firstSig: 'jstlpVault()',
    lastHash: '0xfc243b08',
    lastSig: 'creatorFeeCollected()',
  },
  {
    file: 'export_chunk_422',
    firstHash: '0xfc2447e4',
    firstSig: 'changeSpiritListCost(uint256)',
    lastHash: '0xffffffff',
    lastSig: 'LOCK8605463013()',
  },
]

export function findFileForHash(hash: string): string | null {
  const hashValue = parseInt(hash, 16)

  for (const range of FILE_RANGES) {
    const firstValue = parseInt(range.firstHash, 16)
    const lastValue = parseInt(range.lastHash, 16)

    if (hashValue >= firstValue && hashValue <= lastValue) {
      return range.file
    }
  }

  return null
}

// Track initialization state
let isInitialized = false
let initPromise: Promise<void> | null = null

/**
 * Initializes the zstd library if it hasn't been initialized yet
 * @returns A promise that resolves when the library is ready
 */
async function initZstd(): Promise<void> {
  if (!isInitialized && !initPromise) {
    initPromise = init().then(() => {
      isInitialized = true
    })
  }
  return initPromise || Promise.resolve()
}

/**
 * Decompresses zstd compressed data
 * @param compressedData - The compressed data as an ArrayBuffer
 * @returns The decompressed data as a string
 */
async function decompressZstd(compressedData: ArrayBuffer): Promise<string> {
  await initZstd()

  // Create a Uint8Array from the ArrayBuffer
  const compressedArray = new Uint8Array(compressedData)

  // Decompress the data
  const decompressedArray = decompress(compressedArray)

  // Convert the decompressed data to a string
  const decoder = new TextDecoder('utf-8')
  return decoder.decode(decompressedArray)
}

/**
 * Fetches the function signature for a given hash
 *
 * @param hash - The function hash to look up (format: 0xHASH or just HASH)
 * @returns A promise that resolves to the function signature or null if not found
 */
export async function getFunctionSignature(hash: string): Promise<string | null> {
  // Normalize the hash format (remove 0x prefix if present)
  const normalizedHash = hash.startsWith('0x') ? hash : `0x${hash}`

  // Find the file that contains this hash
  const fileName = findFileForHash(normalizedHash)
  if (!fileName) {
    return null
  }

  try {
    // Fetch the file at runtime as an ArrayBuffer
    const response = await fetch(`/tx-decoder-tmp/${fileName}`)
    if (!response.ok) {
      console.error(`Failed to fetch ${fileName}: ${response.statusText}`)
      return null
    }

    // Get the compressed data as an ArrayBuffer
    const compressedData = await response.arrayBuffer()

    // Decompress the file content
    const fileContent = await decompressZstd(compressedData)

    // Search for the hash in the file
    // Format in file is: 0xHASH,functionSignature(param1,param2)
    const lines = fileContent.split('\n')
    for (const line of lines) {
      if (line.startsWith(normalizedHash + ',')) {
        // Extract the function signature (everything after the comma)
        return line.substring(normalizedHash.length + 1)
      }
    }

    return null
  } catch (error) {
    console.error(`Error fetching function signature for hash ${normalizedHash}:`, error)
    return null
  }
}
