name: 'Lint'
on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_OPTIONS: --max-old-space-size=2048

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/workflows/yarn

      - name: Run lint checks
        run: npx next lint

      - uses: CatChen/eslint-suggestion-action@v4.1.9
        with:
          request-changes: true # optional
          fail-check: true # optional
          github-token: ${{ secrets.GITHUB_TOKEN }} # optional
          directory: './' # optional
          targets: 'src' # optional
