name: Unit tests
on:
  pull_request:
  push:
    branches:
      - eternalsafe

permissions:
  contents: read
  checks: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_OPTIONS: --max-old-space-size=2048

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/workflows/yarn

      - name: Run tests (push)
        if: github.event_name == 'push'
        run: yarn test:ci

      - name: Annotations and coverage report (pull request)
        if: github.event_name == 'pull_request'
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          skip-step: install
          annotations: failed-tests
          package-manager: yarn
          test-script: yarn test:ci
          github-token: ${{ secrets.GITHUB_TOKEN }}
